services:
  server:
    image: szurubooru/server:latest
    restart: unless-stopped
    depends_on:
      - sql
    environment:
      POSTGRES_HOST: sql
      THREADS: 6
    env_file:
      - szuruboorusync.env
    volumes:
      - ./szurubooru/data:/data

  client:
    image: szurubooru/client:latest
    restart: unless-stopped
    depends_on:
      - server
    environment:
      BACKEND_HOST: server
      BASE_URL:
    env_file:
      - szuruboorusync.env
    volumes:
      - ./szurubooru/data:/data:ro
    ports:
      - "4480:80"

  sql:
    image: postgres:11-alpine
    restart: unless-stopped
    env_file:
      - szuruboorusync.env
    volumes:
      - ./szurubooru/pgdata:/var/lib/postgresql/data
    ports:
      - "45432:5432"
      
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
      - HEADLESS=true
      - DISABLE_MEDIA=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8191"]
      interval: 5s
      timeout: 5s
      retries: 10
      
  gelbooru-sync:
    image: sharpsalat/gelboorusync:latest
    restart: unless-stopped
    depends_on:
      server:
        condition: service_started
      flaresolverr:
        condition: service_healthy
    environment:
      BACKEND_HOST: server
      FLARERESOLVERR_HOST: flaresolver
    env_file:
      - szuruboorusync.env
    volumes:
      - ./szurubooru/gelboorudata:/app/data